maxfordham/ipyautoui

- docs/autoui.ipynb
- docs/autovuetify.ipynb
- src/ipyautoui/_utils.py
- src/ipyautoui/custom/editgrid.py
- Removed obj_from_string
- Added traceback to edit grid
> Removed obj_from_string

- .vscode/settings.json
- src/ipyautoui/custom/editgrid.py
> 32-value-setter-not-working-in-ipyautouicustomeditgridbaseform

- src/ipyautoui/custom/editgrid.py
- Added traitlets value to GridWrapper where the value property represents the raw data with the field names. The data property that exists within the DataGrid is set with the titles and any other properties such as rounding, etc.
- Simplified code in edit grid following this.
> Edit grid updates

- src/ipyautoui/custom/editgrid.py
traceback was not showing rejected columns correctly.
Updated to use XOR operator
> Editgrid bug

- src/ipyautoui/custom/multiselect_search.py
multiselect search has been updated to support traitlets
> Updates multiselect search widget

- src/ipyautoui/custom/editgrid.py
- Removed custom datetime renderer out of EditGrid
- Added order_cols input parameter
> Editgrid update

- src/ipyautoui/custom/editgrid.py
updates to datahandler used within EditGrid
> Editgrid db

- src/ipyautoui/custom/editgrid.py
- src/ipyautoui/custom/iterable.py
- src/ipyautoui/test_schema.py
makes it possible to specify custom UI's for editing and adding row values
required for `aectemplater`
> ✨ add row UI controls edit grid

- src/ipyautoui/custom/editgrid.py
- This was lagging out the app when opening and closing the baseform
> Removed _reload_all_data from _display_grid. 

- docs/autoui.ipynb
- docs/test.complexaui.json
- src/ipyautoui/autoipywidget.py
- src/ipyautoui/constants.py
- src/ipyautoui/custom/iterable.py
- src/ipyautoui/custom/showhide.py
- src/ipyautoui/test_schema.py
fixes "Fix formatting or Arrays in AutoUi" action in `aectemplater-release` project
> 46-arrays-and-objects-loose-their-title-and-description-in-autoui

- docs/autoui.ipynb
- docs/test.complexaui.json
- src/ipyautoui/autoipywidget.py
- src/ipyautoui/automapschema.py
- src/ipyautoui/test_schema.py
- added customisation options to AutoObject
- improved support of pydantic enums --> dropdown widget
> ✨ add customisation support auto object

- src/ipyautoui/custom/editgrid.py
- Added methods for setting and moving rows.
- Added input parameter to set index of data grid to start from 1.
> Grid wrapper moving rows

- src/ipyautoui/custom/editgrid.py
- Made selected_keys method generic.
- Added get_selected_data method.
- Updated selected_rows method.
- Updated delete method in EditGrid to use selected_keys.
- Other bug fixes within EditGrid and GridWrapper
> Selected keys issue

- docs/autoui-simple.ipynb
- docs/autoui.ipynb
- docs/autovuetify.ipynb
- docs/custom-renderers.ipynb
- docs/editgrid.ipynb
- docs/validation.ipynb
- requirements.txt
- src/ipyautoui/_utils.py
- src/ipyautoui/autodisplay.py
- src/ipyautoui/autodisplayfile_renderers.py
- src/ipyautoui/autoipywidget.py
- src/ipyautoui/automapschema.py
- src/ipyautoui/autoui.py
- src/ipyautoui/autovjsf.py
- src/ipyautoui/constants.py
- src/ipyautoui/custom/decision_branch.py
- src/ipyautoui/custom/editgrid.py
- src/ipyautoui/custom/selectdir.py
- src/ipyautoui/custom/workingdir.py
- src/ipyautoui/test_schema.py
a more generic method for creating a route to a file location
> Add-`selectdir.py`-to-deprecate-`workingdir.py`

- docs/autovuetify.ipynb
- docs/demo.ipynb
- src/ipyautoui/autoipywidget.py
- src/ipyautoui/automapschema.py
- src/ipyautoui/autovjsf.py
- src/ipyautoui/autowidgets.py
- src/ipyautoui/custom/editgrid.py
- src/ipyautoui/custom/save_buttonbar.py
- src/ipyautoui/demo_schemas/core_ipywidgets.py
- src/ipyautoui/demo_schemas/nullable_core_ipywidgets.py
- tests/test_autoipywidget.py
- tests/test_automapschema.py
- tests/test_autoui.py
- tests/test_custom.py
- tests/test_editgrid.py
- tests/testdata/test_auto_read_file.json
- Added functionality to be able to make any core ipywidget nullable.
> ✨add nullable fields

- src/ipyautoui/custom/editgrid.py
- tests/test_editgrid.py
- Created class that extends AutoObject to update the order property based on which rows are visible in the DataGrid.
> 84 editgrid filtered view

- src/ipyautoui/custom/buttonbars.py
- src/ipyautoui/custom/editgrid.py
copy dialogue not fully integrated, and datahandler as it previously was... 
but merging what has been done - can pick it up again in the future...
> 98-editgrid-datahandler-review-and-copy-dialogue

- src/ipyautoui/autodisplay_renderers.py
- src/ipyautoui/automapschema.py
- src/ipyautoui/custom/fileupload.py
- tests/custom/test_buttonbars.py
- tests/test_autoipywidget.py
fixes `fileupload.FIleUploadToDir` error associated with bug relating to Nullable fields... 
there is now error capture to generic dict terms
> Fix attach nullable field for dict fields

- src/ipyautoui/custom/editgrid.py
> Editgrid reorder fns onsave

- src/ipyautoui/custom/editgrid.py
- Updated index moving in AutoGrid.
- Can now move indexes in both normal and transposed view.
> Fix swap rows

- src/ipyautoui/__init__.py
- src/ipyautoui/_dev_sys_path_append.py
- src/ipyautoui/autodisplay.py
- src/ipyautoui/autodisplay_renderers.py
- src/ipyautoui/autoipywidget.py
- src/ipyautoui/automapschema.py
- src/ipyautoui/autoui.py
- src/ipyautoui/autovjsf.py
- src/ipyautoui/autowidgets.py
- src/ipyautoui/custom/__init__.py
- src/ipyautoui/custom/_dev_sys_path_append.py
- src/ipyautoui/custom/autogrid.py
- src/ipyautoui/custom/buttonbars.py
- src/ipyautoui/custom/decision_branch.py
- src/ipyautoui/custom/editgrid.py
- src/ipyautoui/custom/filechooser.py
- src/ipyautoui/custom/filesindir.py
- src/ipyautoui/custom/fileupload.py
- src/ipyautoui/custom/iterable.py
- src/ipyautoui/custom/loadproject.py
- src/ipyautoui/custom/markdown_widget.py
- src/ipyautoui/custom/outputlogging.py
- src/ipyautoui/custom/selectdir.py
- src/ipyautoui/custom/showhide.py
- src/ipyautoui/custom/urlimagelink.py
- src/ipyautoui/custom/workingdir.py
this means that you no longer have to comment out code in the __init__.py file before packaging! 
✨
> 132 move the dev only code out of the   init  py files

- src/ipyautoui/autowidgets.py
Disabling Nullable UI element is now possible after adding traitlets variable `disabled` with observation where the ToggleButton is disabled and so is the widget instance.
> 💄 ✨ Added disabled traitlet to nullable

- src/ipyautoui/autowidgets.py
- Nullable disables upon instantiation if `disabled` is defined in field schema.
> 💄 🐛 Added disable method to set Nullable state if disabled in schema

- src/ipyautoui/autowidgets.py
- src/ipyautoui/custom/editgrid.py
- src/ipyautoui/custom/iterable.py
- src/ipyautoui/custom/title_description.py
- src/ipyautoui/demo_schemas/nested.py
- src/ipyautoui/demo_schemas/ruleset.py
- tests/test_automapschema.py
- tests/test_demo.py
created a `TitleDescription` base class that is inherited by both EditGrid and Iterable... should probs add to AutoObject too...
> 🐛-fix-title-and-description-for-iterables

- docs/demo.ipynb
- src/ipyautoui/_utils.py
- src/ipyautoui/autoipywidget.py
- src/ipyautoui/automapschema.py
- src/ipyautoui/custom/widgetcaller_error.py
- src/ipyautoui/demo_schemas/__init__.py
- src/ipyautoui/demo_schemas/ruleset.py
- tests/test_automapschema.py
hacky fix in automapschema to solve nested definitions  problem. review again! add a demo to highlight the issue.
improved error reporting widget
> 🚑-fix-AutoObject-show_title-bug-and-nested-definitions

- src/ipyautoui/custom/editgrid.py
- tests/test_demo.py
- Check that a selection exists within the array before trying to set ui_delete and ui_edit.
- Fixed test_show_raw test as PosixPath was being compared to a string which was causing the test to fail.
> Fix delete observation

- docs/autoui.ipynb
- environment-dev.yml
- src/ipyautoui/autoipywidget.py
- src/ipyautoui/autowidgets.py
- src/ipyautoui/custom/selectdir.py
- src/ipyautoui/custom/selectfrom.py
- src/ipyautoui/custom/showhide.py
- src/ipyautoui/demo_schemas/nested_editable_datagrid.py
selectfrom is a simple SelectMuliple with a programmable button
> added selectfrom and made showhide and nested more usable

- src/ipyautoui/custom/halo_decorator.py
added halo decorator - moved from private `aectemplater` package
> added `halo_decorator` @ohensby

- src/ipyautoui/autodisplay.py
- src/ipyautoui/autoipywidget.py
- src/ipyautoui/automapschema.py
- src/ipyautoui/autowidgets.py
- src/ipyautoui/custom/date_string.py
- src/ipyautoui/demo_schemas/__init__.py
- src/ipyautoui/demo_schemas/array_examples.py
- src/ipyautoui/demo_schemas/array_object_dataframe.py
- src/ipyautoui/demo_schemas/core_ipywidgets.py
- src/ipyautoui/demo_schemas/null_and_required.py
- src/ipyautoui/demo_schemas/override_ipywidgets.py
- tests/test_automapschema.py
- tests/test_demo.py
- tests/test_demo_schemas.py
did some work on nullables - 
began updating the way that `automapschema` works to put more the mapping functions out of the widgets
> 186-update-handling-of-nullable-fields-for-pydantic-v2

- src/ipyautoui/autoanyof.py
- src/ipyautoui/autobox.py
- src/ipyautoui/automapschema.py
- src/ipyautoui/autoobject.py
- src/ipyautoui/demo_schemas/complex_serialization.py
- src/ipyautoui/demo_schemas/core_ipywidgets.py
- tests/test_automapschema.py
add initial support for AnyOf widget that allows the user to chose what widget they would like to use
> ✨ improve handling of nullable. add support for `AnyOf` widget

- src/ipyautoui/autoanyof.py
- src/ipyautoui/automapschema.py
- src/ipyautoui/autoobject.py
- src/ipyautoui/autovjsf.py
- src/ipyautoui/custom/__init__.py
- src/ipyautoui/custom/iterable.py
- src/ipyautoui/demo_schemas/__init__.py
- src/ipyautoui/demo_schemas/recursive_array.py
rewrite of `iterable.py` module. uses traits rather than __init__ kwargs. much simplified.
> REFACTOR-iterable-array-widget-to-use-traits

- src/ipyautoui/custom/autogrid.py
♻️ Update VegaExpr so instead sets to default_renderer
> ✨ Can hide NaN and set decimal places

- src/ipyautoui/custom/autogrid.py
Can now hide NaN if global_decimal_places set to None
> 🐛 Fix text_value VegaExpr for hide_nan parameter

- .github/workflows/test-python-package.yml
- README.md
> 📝 Add workflow badge to README.md

- src/ipyautoui/automapschema.py
- src/ipyautoui/autoobject.py
- src/ipyautoui/autoui.py
- src/ipyautoui/custom/date_string.py
- src/ipyautoui/custom/fileupload.py
- src/ipyautoui/custom/iterable.py
- src/ipyautoui/custom/multi_toggle_buttons.py
- src/ipyautoui/custom/multiselect_search.py
- src/ipyautoui/nullable.py
add DatetimePickerString and update DatePickerString which inherit DatetimePicker and DatePicker to include a stateful `_value` trait that is a jsonable date(time) string
> FIX-datetime-widgets

- docs/demo.ipynb
- src/ipyautoui/_utils.py
- src/ipyautoui/demo_schemas/__init__.py
- src/ipyautoui/demo_schemas/ruleset.py
adds a real-world example demonstrating how the UI can be customised to the user needs
> add `ScheduleRuleset` example

- src/ipyautoui/automapschema.py
- src/ipyautoui/demo_schemas/core_ipywidgets.py
- tests/test_automapschema.py
- tests/test_demo_schemas.py
- tests/testdata/test_auto_read_file.json
this add the select multiple widget if a list select from enum is given
> ✨ add tagsinput and select multiple as a standard options

- src/ipyautoui/autodisplay.py
- src/ipyautoui/custom/__init__.py
- src/ipyautoui/custom/fileupload.py
- src/ipyautoui/custom/iterable.py
- src/ipyautoui/demo_schemas/__init__.py
- src/ipyautoui/demo_schemas/complex_serialization.py
- tests/custom/test_fileupload.py
fixes file(s) upload to dir widgets
> FIX-file-upload-to-dir-following-iterable-update

- src/ipyautoui/_utils.py
- src/ipyautoui/custom/autogrid.py
- tests/test_autogrid.py
json string type to python type mapping from `_utils.py`
> 🐛 fixes broken test and uses

- src/ipyautoui/custom/iterable.py
There was an issue with the initial add button not showing after removing the last box meaning that it wasn't possible to add again. I've resolved this by ensuring this is displayed after removing the last box.
> Fix array remove row

- .github/workflows/deploy-book.yml
- README.md
update readme / hopefully rebuild docs
> Udpate readme to show docs

- src/ipyautoui/watch_validate.py
- tests/test_maplocal_openfile.py
✅ Comment out maplocal test as requires user specific config
> ✨ Implement show_validation

- src/ipyautoui/automapschema.py
- src/ipyautoui/custom/__init__.py
- src/ipyautoui/custom/iterable.py
- src/ipyautoui/custom/multi_toggle_buttons.py
- src/ipyautoui/demo_schemas/core_ipywidgets.py
- tests/test_autogrid.py
- tests/test_autoui.py
- tests/test_demo_schemas.py
adds a simple Dictionary widget that uses a key not a index for an array. 
TODO: add `AutoDictionary`
> Readd-Dictionary-iterable

- src/ipyautoui/custom/selectandclick.py
- tests/test_autogrid.py
- Hotfix to resolve SelectAndClick setting options issue when all the values are selected.
- Replace `map_options` with `index_to_key` attribute.
> Select and click update

- src/ipyautoui/custom/urlimagelink.py
♻️ Refactor functionality
🐛 Fix style classes
> 🐛 Fix UrlImageLink

- src/ipyautoui/autoform.py
- src/ipyautoui/automapschema.py
- src/ipyautoui/autoui.py
- src/ipyautoui/custom/iterable.py
- src/ipyautoui/custom/selectandclick.py
- src/ipyautoui/demo_schemas/root_simple.py
- src/ipyautoui/watch_validate.py
- tests/test_autoobject.py
- tests/test_autoui.py
- tests/test_demo.py
- tests/test_demo_schemas.py
💥 MAJOR REFACTOR.
AutoUi is now a builder function, not a class
it selects what widget (typically a container widget) to use and returns that widget.
> Refactor-autoui

- src/ipyautoui/custom/combobox_mapped.py
Updates widget value and the private value attribute via observer
> 🐛 Set widget value in setter

- src/ipyautoui/custom/selectandclick.py
Must set value to empty list before setting options otherwise bugs out
> 🚑 Fix AddMultiple and RemoveMultiple

- src/ipyautoui/autoobject.py
🐛 Resolved other issues in testing cells
> 🐛 Fix disabled observation

- docs/buttonbar_extended.ipynb
- src/ipyautoui/constants.py
- src/ipyautoui/custom/buttonbars.py
- src/ipyautoui/custom/editgrid.py
🐛 Fix value in EDIT_BUTTON_KWARGS
📝 Add example to extend CrudButtonBar
> 🐛 Implement CrudView into CrudButtonBar

- docs/autoui.ipynb
- docs/demo.ipynb
- docs/editgrid.ipynb
- environment.yml
- src/ipyautoui/autoform.py
- src/ipyautoui/autoobject.py
- src/ipyautoui/autoui.py
- src/ipyautoui/custom/editgrid.py
- src/ipyautoui/demo_schemas/__init__.py
- src/ipyautoui/demo_schemas/editable_datagrid_with_nullable.py
- src/ipyautoui/nullable.py
- src/ipyautoui/watch_validate.py
- tests/test_autoform.py
- tests/test_autoobject.py
- tests/test_editgrid.py
this adds a show hide null values toggle button - defaults to hide null
> 263 add hide null values trait and toggle

- src/ipyautoui/autoform.py
- src/ipyautoui/autoobject.py
- tests/test_autoobject.py
Replace try-except with type check of instance
> 🐛 Change null displays on value change

- src/ipyautoui/autoform.py
- src/ipyautoui/autoobject.py
- src/ipyautoui/autoui.py
- src/ipyautoui/constants.py
- tests/test_autoobject.py
> 🐛 Resolve bn_shownull display issue

- docs/autovuetify.ipynb
- src/ipyautoui/autovjsf.py
- tests/test_autovjsf.py
simple bugfix of `AutoVjsf` widget
> 286 initialising autovjsf throws attributeerror

- src/ipyautoui/custom/executetasks.py
- src/ipyautoui/custom/timeelapsed.py
> 🐛 Reset spinners and times shown on start

- src/ipyautoui/custom/svgspinner.py
Allows passing of ipywidget related input parameters
> 🐛 Add kwargs to SvgSpinner

- docs/demo.ipynb
- docs/editgrid.ipynb
- environment.yml
- pyproject.toml
- src/ipyautoui/_utils.py
- src/ipyautoui/custom/autogrid.py
- src/ipyautoui/custom/datagrid.py
- src/ipyautoui/custom/editgrid.py
- src/ipyautoui/demo_schemas/multiindex_editable_grid.py
- tests/test_autogrid.py
- tests/test_editgrid.py
- tests/test_maplocal_openfile.py
fixes the mis-aligned context menu bug in ipydatagrid 🚀
at the same time as this ^ fix ipydatagrid made the backend `_data` value a dataframe rather than a list of dicts -
so this PR chases throught that change also
> 🐛 Resolve context menu positioning bug & backend `_data` issue

- README.md
Following name change of workflow.
> 📃 Fix workflow badge

- docs/issue-330.ipynb
- src/ipyautoui/autoobject.py
- src/ipyautoui/watch_validate.py
- tests/test_autoobject.py
Any non-nullable fields should always have a value.
> 🐛 Ensure value is set for non-nullable fields in AutoObject

- .gitignore
- docs/issue-336.ipynb
- src/ipyautoui/custom/filechooser.py
> 336-inconsistency-between-value-and-selected-in-customfilechooser

- .gitattributes
- .github/workflows/test-and-lint.yml
- .gitignore
- pixi.lock
- pyproject.toml
fixes CI issue and pixi simplifies CI setup
> 348-ci-failing

- docs/autodisplay.ipynb
- docs/autoui.ipynb
- docs/autovuetify.ipynb
- docs/buttonbar_extended.ipynb
- docs/demo.ipynb
- docs/editgrid.ipynb
- docs/issue-178.ipynb
- docs/issue-330.ipynb
- docs/validation.ipynb
- pixi.lock
- pyproject.toml
- src/ipyautoui/__init__.py
- src/ipyautoui/custom/__init__.py
- src/ipyautoui/custom/jsonable_dict.py
- src/ipyautoui/custom/showhide.py
- src/ipyautoui/demo_schemas/override_ipywidgets.py
this gives very simple support for users to input a json string. it warns / does not update if the string is invalid.
> ✨add jsonable dict.

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- src/ipyautoui/autoui.py
> Setup devcontainer

- docs/autoui.ipynb
- src/ipyautoui/autoobject.py
- src/ipyautoui/autoui.py
- tests/test_autoobject.py
adds support for minor (no change to widgets or keys) changes to the schema / model in-place
> 192-update-autoui-on-schema-change

- pixi.lock
- pyproject.toml
Issues with searching in the grid in latest version
> ⬇️ Downgrade and pin ipydatagrid to v1.3.2

- src/ipyautoui/_utils.py
- src/ipyautoui/autoanyof.py
- src/ipyautoui/autobox.py
- src/ipyautoui/automapschema.py
- src/ipyautoui/autoobject.py
- src/ipyautoui/custom/autogrid.py
- src/ipyautoui/custom/executetasks.py
- src/ipyautoui/custom/fileupload.py
- src/ipyautoui/custom/iterable.py
- src/ipyautoui/demo_schemas/complex_serialization.py
- src/ipyautoui/demo_schemas/ruleset.py
- tests/test_autogrid.py
- tests/test_autoobject.py
minor fixes to __init__ methods to avoid passing unexpected kwargs to super().__init__() and other things. reduce no of warnings when running tests to 4.
> fix warning and general tidy up
