maxfordham/ipyautoui

- docs/__init__.py
- docs/autodisplay.ipynb
- docs/demo.ipynb
- src/ipyautoui/autodisplayfile_renderers.py
- src/ipyautoui/custom/markdown_widget.py
- src/ipyautoui/env.py
- tests/constants.py
- tests/filetypes/eg_md.md
- tests/filetypes/eg_vega_waterfall.vg.json
- tests/test_env.py
pdf, markdown and vega all require paths to be relative to the rendering notebook rather than the file that is rendered. This PR adds support for this. It does this by getting the notebook dir (`pathlib.Path(".").absolute()`), or if explicitly given (robust -method) by using the `IPYAUTOUI_ROOTDIR` env var.
> ✨-support-rebasing-relative-data-to-notebook-dir

- docs/autoui.ipynb
- docs/demo.ipynb
- src/ipyautoui/autoipywidget.py
- src/ipyautoui/automapschema.py
- src/ipyautoui/autoui.py
- src/ipyautoui/autowidgets.py
- src/ipyautoui/custom/decision_branch.py
- src/ipyautoui/custom/editgrid.py
- src/ipyautoui/custom/iterable.py
- src/ipyautoui/demo_schemas/core_ipywidgets.py
- tests/test_autoui.py
- tests/testdata/test_auto_read_file.json
PR adds the `transposed` trait to `custom.editgrid.DataGrid` which transposes the UI view of the DataGrid.
NOTE:
- it does not change the `_value` of the AutoGrid trait, it is intended to allow for a different UI based on the same data
TODO:
- add UI button to toggle between transposed / not transposed view
- define how the formatting gets set / reset when toggling between the views
> ✨add-transposed-view-to-EditGrid

- src/ipyautoui/custom/editgrid.py
Enforce conversion of datagrid_index_name to tuple when instantiating GridSchema.
- This is because JSON schema does not have tuples so it will be a list in JSON form, therefore, we must convert it to tuple in Python upon passing the object to EditGrid.
> Enforce conversion of datagrid_index_name to tuple

- src/ipyautoui/custom/editgrid.py
(ipydatagrid doesn't support dataframe with no columns)
> if empty dataframe, add a default row if Grid is transposed

- src/ipyautoui/custom/editgrid.py
Made it so if index of data in grid is a subset of the grid schema then it is still operational within the class.
E.g. if dataframe passed to setter had the columns ["Guid" , "Name"] then it would still be possible to set it.
This was because there were issues with setting data when only wanting to show certain columns.
> Data subsets to work in autogrid

- src/ipyautoui/custom/autogrid.py
- tests/test_autogrid.py
🐛 Updated `records` AutoGrid method to return correct data after reordering of indexes.
✅ 3 new tests added to check `records` AutoGrid method, and that a strict subset of indexes can be passed to the AutoGrid `order` traitlet i.e. `("floater",)` can be passed to AutoGrid's `order` where the grid has 2 indexes: "floater", and "string".
> Autogrid records issue

- src/ipyautoui/autowidgets.py
- src/ipyautoui/demo_schemas/nested.py
simple fix - the `Nullable` widget wasn't watching `_value` trait so wasn't working with custom widgets
> 🐛-fix-value-watcher-for-nullable-arrays

- src/ipyautoui/_utils.py
- src/ipyautoui/autodisplay_renderers.py
- src/ipyautoui/demo_schemas/ruleset.py
create simple reusable functions for previewing strings: 
`preview_json_string`, `preview_yaml_string`, `preview_vega_json`, `preview_vegalite_json`, `preview_text_string`
this allows these functions to be used independently of the `getbytes` function which retrieves data from: path, request or callable
> ✨-generalise-autodisplay_rendererers

- src/ipyautoui/custom/editgrid.py
- Upon saving an edited instance (when using a datahandler), clear the selections, and then reselect after reloading the grid data.
> 🚑 🐛 Reselect selection after editing instance

- .env
- .vscode/launch.json
- docs/autodisplay.ipynb
- maplocal_example.py
- src/ipyautoui/_dev_sys_path_append.py
- src/ipyautoui/_utils.py
- src/ipyautoui/autodisplay.py
- src/ipyautoui/autodisplay_renderers.py
- src/ipyautoui/custom/_dev_sys_path_append.py
- src/ipyautoui/custom/autogrid.py
- src/ipyautoui/custom/buttonbars.py
- src/ipyautoui/custom/decision_branch.py
- src/ipyautoui/custom/editgrid.py
- src/ipyautoui/custom/filechooser.py
- src/ipyautoui/custom/filesindir.py
- src/ipyautoui/custom/fileupload.py
- src/ipyautoui/custom/iterable.py
- src/ipyautoui/custom/loadproject.py
- src/ipyautoui/custom/markdown_widget.py
- src/ipyautoui/custom/outputlogging.py
- src/ipyautoui/custom/selectdir.py
- src/ipyautoui/custom/showhide.py
- src/ipyautoui/custom/title_description.py
- src/ipyautoui/custom/urlimagelink.py
- src/ipyautoui/custom/widgetcaller_error.py
- src/ipyautoui/custom/workingdir.py
- src/ipyautoui/demo_schemas/_dev_sys_path_append.py
- src/ipyautoui/demo_schemas/ruleset.py
- tests/test_maplocal_openfile.py
deprecated `mf_file_utilities`. 
uses `maplocal` to map files on a shared drive from a server App to the users local machine. 
see `maplocal-mxf` repo (private) for an example of how to use it on an on-prem server using repo2docker.
see example  `test_maplocal_openfile.py` for an example of using it to map wsl to windows c drive
> ⬆️-use-maplocal-and-deprecate-mf_file_utilities

- src/ipyautoui/_utils.py
The indent level was incorrect in one of the code branches, making it impossible to import under ipyautoui under some circumstances.
PS Thanks for the excellent package!
> Fix indentation of open_path

- .github/workflows/test-python-package.yml
Removed as we need the tests to run ideally if files in the root change too e.g. the environment file
> 🔥 Remove paths filter

- src/ipyautoui/custom/autogrid.py
- src/ipyautoui/custom/editgrid.py
When settings an empty list (or tuple) to an EditGrid object, set an empty dataframe to EditGrid.grid.data. Before these changes, it was setting a default value when trying to set to an empty list which meant that there could never be an empty EditGrid.
> ♻️ Don't set default when trying to set empty list

- README.md
- src/ipyautoui/__init__.py
- src/ipyautoui/custom/fileupload.py
see here:
https://github.com/voila-dashboards/voila/issues/807
ipyvuetify file upload limit isn't constained to 10mb avoiding the issue so it has been added as an option to use with the `FilesUploadToDir` widget
> FEATURE-add-vuetify-fileupload-widget-to-bugfix-10mb-max-file-size-issue

- src/ipyautoui/custom/filedownload.py
- src/ipyautoui/custom/svgspinner.py
🐛 Set output widget for SVG spinner to fixed width
> 🐛 Clear output after file download triggered

- src/ipyautoui/custom/filechooser.py
- src/ipyautoui/custom/iterable.py
- tests/custom/test_filechooser.py
adds all the keyword arguments from the orginal filechooser __init__ to ensure that they are present in the argspec
> 297-filter_pattern-in-a-field-does-not-get-sent-to-filechooser

- src/ipyautoui/autoobject.py
Setting the value of an AutoObject that contains a nullable NestedObject now appears if the value set is not None. If it is None the widget is hidden as expected.
The reason this wasn't working was because there was an if statement that was checking whether the value passed is a list or dict. There was no "else" statement to deal with this. From a review, it looks like this "if" statement doesn't need to exist at all so it has been removed.
> 🐛 Fix display issue of nested widgets with nullable

- src/ipyautoui/autobox.py
- src/ipyautoui/autoobject.py
- src/ipyautoui/nullable.py
Updated formatting so that a spacer is added to widgets of type array.
Ensured that indent is set to true for widgets of type array.
> 🐛 Fix indenting of widgets in AutoObject

- src/ipyautoui/_utils.py
- src/ipyautoui/autoobject.py
- src/ipyautoui/nullable.py
- tests/test_utils.py
Implementing use of `pd.isnull` where applicable.
Before we were just checking for `None`, however, pandas data frame returns `nan` and therefore was not being captured by the if statement correctly. 
The issue was caused by this [commit](https://github.com/maxfordham/ipyautoui/commit/e986b9a4ca287f82e733502b10faa07aa9bbc198) and will be reverted in this PR.
To finally resolve this issue, an `is_null` function has been created and used in place of `pd.isnull`.
> ♻️ Create is_null function and implement where pd.isnull is used

- docs/environment.yml
Fixed by pinning `nbclient>=0.7.4`
> 👷‍♂️ Fix deploy book workflow

- src/ipyautoui/custom/filechooser.py
- tests/custom/test_filechooser.py
This pull requests fixes a couple of issues with. setting the value of a `FileChooser` widget. 
There were two separate issues, though they had similar fixes.
The first issue was that setting the value to a file that did not exist was impossible. This code demonstrates that bug:
```python
import tempfile
from pathlib import Path
from ipyautoui.custom.filechooser import FileChooser
fc = FileChooser()
with tempfile.TemporaryDirectory() as tmpdirname:
tmp_path = Path(tmpdirname)
fc.value = tmp_path / "does_not_exist.txt"
assert fc.selected_filename == "does_not_exist.txt"  # Fails because fc.selected_filename is ""
```
The root cause in this case is [this line](https://github.com/maxfordham/ipyautoui/blob/main/src/ipyautoui/custom/filechooser.py#L68), where I think the correct behavior is to …
> Fix bugs in setting FileChooser value

- src/ipyautoui/_utils.py
- src/ipyautoui/demo_schemas/override_ipywidgets.py
- tests/test_automapschema.py
For example, the function `traits_in_kwargs` now checks for `_value` in the function if `value` is present in `kwargs`.
> 🐛 Check for private traits with similar naming in `kwargs`

- src/ipyautoui/custom/title_description.py
Resolves the issue where empty parentheses were being shown.
> 🐛 Only set html_unit value if unit defined

- docs/issue-17.ipynb
- docs/issue-332.ipynb
- src/ipyautoui/autoform.py
- src/ipyautoui/automapschema.py
- src/ipyautoui/custom/autogrid.py
- tests/test_autogrid.py
If key-value pair missing in value passed to GridSchema, then use the default value as defined in the schema when coercing the data.
> ✨ GridSchema: if value missing, use default value from schema

- pyproject.toml
- src/ipyautoui/automapschema.py
- src/ipyautoui/autoobject.py
- src/ipyautoui/custom/iterable.py
- src/ipyautoui/watch_validate.py
- tests/test_autogrid.py
- tests/test_automapschema.py
- tests/test_editgrid.py
The JSON schema specification has been updated to allow sibling keys alongside `$ref` keys so it is no longer required to wrap the `$ref` key in an `allOf` array with a single `$ref` element. The method `model_json_schema` has been updated in Pydantic 2.9 to reflect this logic.
This means that the JSON schema specification does not adhere to the [jsonref specification](http://jsonref.org/#ref) anymore which states:
`All other properties of an object containing a $ref key are ignored.`
By setting `merge_props=True`, the jsonref `replace_refs` ignores this specific part of the jsonref spec.
Reference issue in `jsonref` repository: https://github.com/gazpachoking/jsonref/issues/68
> 🐛 Set `merge_props` to True when using `replace_refs`

- docs/demo.ipynb
- pixi.lock
- pyproject.toml
- src/ipyautoui/constants.py
- src/ipyautoui/custom/autogrid.py
- src/ipyautoui/demo_schemas/override_ipywidgets.py
- tests/constants.py
- tests/instance_spec.json
fixes issue where the grid would get cleared if the `order` trait was being used to filter as it wasn't mapping the names to the titles
> BUGFIX-editgrid-set-order-clears-grid

- src/ipyautoui/custom/buttonbars.py
- src/ipyautoui/custom/editgrid.py
This is required for any traits that are defined.
Also resolved issue with the support button used in `EditGrid`.
> 🐛 EditGrid: Pass kwargs to parent class

- src/ipyautoui/custom/editgrid.py
Only pass kwargs to EditGrid that do not have an associated trait in AutoGrid.
> 🐛 EditGrid: Only pass necessary kwargs

- src/ipyautoui/custom/editgrid.py
fixes AutoUi callable for EditGrid objects. 
therefore fixes EditGrid examples in the demo.
TODO: still need to fix the nested nullable object example
> 🐛FIX: `_set_children` -> `set_children_editgrid` to prevent name overides on inheritance

- .github/workflows/pypi-publish.yml
NOTES.
- configured the org / repo / action / env as a trusted publisher on pypi
- added an env to GH repo called `pypi`
> 🤖add CI to build publish to pypi on tag. Need to verify it works on next tag.
